# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomeasure < Formula
  desc "A tool to measure the content of your codebase"
  homepage "https://github.com/lordvidex/gomeasure"
  version "0.1"
  license "MIT"

  on_macos do
    url "https://github.com/lordvidex/gomeasure/releases/download/v0.1/gomeasure_0.1_darwin_all.tar.gz"
    sha256 "259859e0f6fd4d3b6f9ca2fab1893d995ff5aa9c6a7e29c4397dc60910b22156"

    def install
      bin.install "gomeasure"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lordvidex/gomeasure/releases/download/v0.1/gomeasure_0.1_linux_amd64.tar.gz"
      sha256 "084afaa71424d98b6e94d82554a48a3100a3569e072faa32cb672e0d17ee9047"

      def install
        bin.install "gomeasure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lordvidex/gomeasure/releases/download/v0.1/gomeasure_0.1_linux_arm64.tar.gz"
      sha256 "71bcfd0635306eb06ac3f78efbe6fac05f66fd4ad7b9d4469ca1ac0f34eacedf"

      def install
        bin.install "gomeasure"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing gomeasure!
      Please consider starring the project at https://github.com/lordvidex/gomeasure
    EOS
  end
end
