# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomeasure < Formula
  desc "A tool to measure the content of your codebase"
  homepage "https://github.com/lordvidex/gomeasure"
  version "0.3.1"
  license "MIT"

  on_macos do
    url "https://github.com/lordvidex/gomeasure/releases/download/v0.3.1/gomeasure_0.3.1_darwin_all.tar.gz"
    sha256 "64175013ae24517a6f80d30cbfaca4e75b153aeff5b81fc97b3e9dcef7cc0837"

    def install
      bin.install "gomeasure"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lordvidex/gomeasure/releases/download/v0.3.1/gomeasure_0.3.1_linux_arm64.tar.gz"
      sha256 "40e9dd951ee6c0334c6e5d2e8ed7cfb21aca5a916edddd714b6872ab5c706b72"

      def install
        bin.install "gomeasure"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lordvidex/gomeasure/releases/download/v0.3.1/gomeasure_0.3.1_linux_amd64.tar.gz"
      sha256 "5f1cf888de1183eb0b538f7eea2951da40011e77435f8b4b2c6dd47363fa741f"

      def install
        bin.install "gomeasure"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing gomeasure!
      Please consider starring the project at https://github.com/lordvidex/gomeasure
    EOS
  end
end
